name: EinTimer
version: '1.1_EN'
main: com.dimitrighg.EinTimer
api-version: '1.21'
authors: [ DimitriGHG ]
description: A lightweight Minecraft Timer for Speedruns in a BastiGHG style.
website: https://dev.dimitrighg.de
commands:
  timer:
    description: Manage the Timer
    usage: /timer> <pause|resume|death|reset|enable>
